/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2024-04-15

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

void TIM6_DAC_IRQHandler()
{
	TIM6->SR &= ~TIM_SR_UIF;
	blinkled();
}

void Set48MHz()
{
	RCC->CR &= ~RCC_CR_PLLON;
	while(RCC->CR & RCC_CR_PLLRDY) {} //until PLL unlocked

	RCC->CFGR |= RCC_CFGR_PLLSRC_HSI_DIV2; //unndeeded?
	RCC->CFGR |= RCC_CFGR_PLLMUL12; //8 / 2 * 12 = 48 MHz
	RCC->CR |= RCC_CR_PLLON; //turn on

	while(!(RCC->CR & RCC_CR_PLLRDY)) {} //until PLL locked

	RCC->CFGR |= RCC_CFGR_SW_1;

	while(!(RCC->CFGR & RCC_CFGR_SWS_1)) {}

	SystemCoreClockUpdate();
}

void init_portc()
{
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODER8_0;
	GPIOC->ODR |= GPIO_ODR_8;
}

void blinkled()
{
	GPIOC->ODR ^= GPIO_ODR_8;
}

void init_tim6()
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM6EN;
	TIM6->ARR = 8000 - 1;
	TIM6->PSC = 1000 - 1;

	TIM6->DIER |= TIM_DIER_UIE;
	NVIC_SetPriority(TIM6_DAC_IRQn, 6);
	NVIC_EnableIRQ(TIM6_DAC_IRQn);
}

void start_tim6()
{
	TIM6->CR1 |= TIM_CR1_CEN;
}

int main(void)
{
	Set48MHz();
	init_portc();
	init_tim6();
	start_tim6();

	while (1)
		{
			for(int i = 0; i < 600000; i++) {}
			//blinkled();
		}
}
